[package]
edition = "2021"
name = "view"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.36.0+1.3.206"
winit = "0.26.1"
